apiVersion: v1
kind: Service
metadata:
  name: mcprobe
spec:
  ports:
  - port: 8080
    name: http-echo
  selector:
    app: mcprobe
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mcprobe
spec:
  template:
    metadata:
      labels:
        app: mcprobe
    spec:
      containers:
      - name: fortio-server
        image: fortio/fortio
        ports:
        - containerPort: 8080
        args:
        - server